name: Build Game for Windows

on:
  push:
    branches:
      - master  # or your desired branch to trigger the build

jobs:
  build:
    runs-on: windows-latest  # or use self-hosted if you have a custom runner

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Install Python 2.7.18
      run: |
        # Install Python 2.7.18 manually on the runner
        $python_installer = "${{ github.workspace }}\src\bin\python\python-2.7.18.msi"
        msiexec /i $python_installer /quiet /norestart

    - name: Configure Python to use bundled Lib
      run: |
        # Set the path to the bundled Python Lib directory
        $python_dir = "${{ github.workspace }}\src\bin\python"
        $lib_dir = "${{ github.workspace }}\src\bin\python\Lib"

        # Set the environment variable to use the bundled Lib directory
        $env:PYTHONPATH = "$lib_dir;$env:PYTHONPATH"

        # Verify the Python environment
        Write-Host "Using Python 2.7.18 from the installed location"
        & "C:\Python27\python.exe" --version

    - name: Install dependencies (py2exe, pyglet, etc.)
      run: |
        # Install dependencies using Python 2.7.18
        & "C:\Python27\python.exe" -m pip install -r requirements.txt

    - name: Build with py2exe
      run: |
        # Run the setup.py to build the project using Python 2.7.18
        & "C:\Python27\python.exe" setup.py py2exe

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: snakes-etc-on-a-plain-win32
        path: release/win32  # Adjust to your actual build output path
