name: Build Game for Windows

on:
  push:
    branches:
      - master  # or your desired branch to trigger the build

jobs:
  build:
    runs-on: windows-latest  # or use self-hosted if you have a custom runner

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Install Python 2.7.18 using MSI installer
      run: |
        $python_installer = "${{ github.workspace }}\src\bin\python\python-2.7.18.msi"
        msiexec /i $python_installer /quiet /norestart

    - name: Verify Python 2.7 installation
      run: |
        python --version
        where python

    - name: Ensure Python 2.7 pip is used
      run: |
        # Ensure the Python 2.7 path is set for this session
        $env:PATH = "C:\Python27\;$env:PATH"
        python -m ensurepip --default-pip  # Ensure pip is installed for Python 2.7
        C:\Python27\Scripts\pip.exe --version  # Show pip version for Python 2.7

    - name: Install pyglet and dependencies using Python 2.7 pip
      run: |
        cd src
        C:\Python27\Scripts\pip.exe install pyglet==1.2
        C:\Python27\Scripts\pip.exe install -r requirements.txt  # Install all other dependencies

    - name: Build with py2exe
      run: |
        cd src
        python setup.py py2exe

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: snakes-etc-on-a-plain-win32
        path: release/win32  # Adjust to your actual build output path
