name: Build Game for Windows

on:
  push:
    branches:
      - master  # or your desired branch to trigger the build

jobs:
  build:
    runs-on: windows-latest  # or use self-hosted if you have a custom runner

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

  name: Set up bundled Python
  run: |
    # Set the path to the bundled Python directory in the repository
    $python_dir = "${{ github.workspace }}\src\bin\python"  # Path relative to the repo root

    # Add bundled Python to the PATH
    $env:PATH = "$python_dir;$env:PATH"  # Add bundled Python to the PATH

    # Verify the Python environment
    Write-Host "Using Python from: $python_dir"
    & "$python_dir\python.exe" --version

    - name: Install dependencies (py2exe, pyglet, etc.)
      run: |
        # Install dependencies using bundled Python
        & "${{ github.workspace }}\src\bin\python\python.exe" -m pip install -r requirements.txt

    - name: Build with py2exe
      run: |
        # Run the setup.py to build the project using the bundled Python
        & "${{ github.workspace }}\src\bin\python\python.exe" setup.py py2exe

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: snakes-etc-on-a-plain-win32
        path: release/win32  # Adjust to your actual build output path
