name: Build Game for Windows

on:
  push:
    branches:
      - master  # or your desired branch to trigger the build

jobs:
  build:
    runs-on: windows-latest  # or use self-hosted if you have a custom runner

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Install Python 2.7.18 using MSI installer
      run: |
        # Install Python 2.7.18 using MSI installer (adjust the path if needed)
        $python_installer = "${{ github.workspace }}\src\bin\python\python-2.7.18.msi"
        msiexec /i $python_installer /quiet /norestart

    - name: Verify Python installation
      run: |
        # Verify Python installation and print the location
        where python
        python --version

    - name: Install pip using bundled ensurepip
      run: |
        # Use bundled ensurepip to install pip if it's not already installed
        python -m ensurepip --default-pip
        python -m pip --version

    - name: Install dependencies (py2exe, pyglet, etc.)
      run: |
        # Install dependencies using pip, pointing to the correct path of requirements.txt
        python -m pip install -r "${{ github.workspace }}\src\requirements.txt"


    - name: Build with py2exe
      run: |
        # Run the setup.py to build the project using Python 2.7.18
        python "${{ github.workspace }}\src\setup.py" py2exe

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: snakes-etc-on-a-plain-win32
        path: release/win32  # Adjust to your actual build output path
