name: Build Game for Windows

on:
  push:
    branches:
      - master  # or your desired branch to trigger the build

jobs:
  build:
    runs-on: windows-latest  # or use self-hosted if you have a custom runner

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Install Python 2.7.18
      run: |
        # Install Python 2.7.18 manually on the runner
        $python_installer = "${{ github.workspace }}\src\bin\python\python-2.7.18.msi"
        msiexec /i $python_installer /quiet /norestart

    - name: Verify Python installation
      run: |
        # Verify Python installation and print the location
        where python

    - name: Install pip for Python 2.7.18
      run: |
        # Install pip using the get-pip.py file from the repository
        $python_exe = "C:\Python27\python.exe"  # Adjust based on where `where python` outputs
        $get_pip_script = "${{ github.workspace }}\src\bin\python\get-pip.py"
        
        # Install pip for Python 2.7.18
        & $python_exe $get_pip_script

    - name: Install setuptools and wheel
      run: |
        # Install setuptools and wheel for compatibility
        & "C:\Python27\python.exe" -m pip install --upgrade setuptools wheel

    - name: Install dependencies (py2exe, pyglet, etc.)
      run: |
        # Install dependencies using pip for Python 2.7.18
        & "C:\Python27\python.exe" -m pip install -r requirements.txt

    - name: Build with py2exe
      run: |
        # Run the setup.py to build the project using Python 2.7.18
        & "C:\Python27\python.exe" setup.py py2exe

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: snakes-etc-on-a-plain-win32
        path: release/win32  # Adjust to your actual build output path
