name: Build Game for Windows

on:
  push:
    branches:
      - master  # or your desired branch to trigger the build

jobs:
  build:
    runs-on: windows-latest  # or use self-hosted if you have a custom runner

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Install Python 2.7.18
      run: |
        # Install Python 2.7.18 manually on the runner
        $python_installer = "${{ github.workspace }}\src\bin\python\python-2.7.18.msi"
        msiexec /i $python_installer /quiet /norestart

    - name: Install pip for Python 2.7.18
      run: |
        # Install pip using the get-pip.py file from the repository
        $python_exe = "C:\Python27\python.exe"
        $get_pip_script = "${{ github.workspace }}\src\bin\python\get-pip.py"
        
        # Install pip for Python 2.7.18
        & $python_exe $get_pip_script

    - name: Configure Python to use bundled Lib
      run: |
        # Set the path to the bundled Python Lib directory
        $python_dir = "${{ github.workspace }}\src\bin\python"
        $lib_dir = "${{ github.workspace }}\src\bin\python\Lib"
