name: Build Game for Windows

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest  # Using GitHub's hosted Windows runner

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Install Python 2.7.18 using MSI installer
      run: |
        $python_installer = "${{ github.workspace }}\src\bin\python\python-2.7.18.msi"
        msiexec /i $python_installer /quiet /norestart

    - name: Verify Python 2.7 installation
      run: |
        python --version
        where python

    - name: Ensure Python 2.7 pip is used
      run: |
        # Ensure Python 2.7 is in the path
        $env:PATH = "C:\Python27\;$env:PATH"
        
        # Ensure pip is installed for Python 2.7
        python -m ensurepip --default-pip
        
        # Use python -m pip instead of calling pip directly
        python -m pip --version

    - name: Install py2exe 0.6.9 from .whl file
      run: |
        # Install py2exe 0.6.9 manually from the .whl file
        python -m pip install "${{ github.workspace }}\src\bin\python\py2exe-0.6.9-py2-none-any.whl"

    - name: Verify py2exe installation
      run: |
        # Verify that py2exe is installed
        python -c "import py2exe; print('py2exe version:', py2exe.__version__)"

    - name: Install pyglet manually (using a specific wheel, if needed)
      run: |
        # Install pyglet manually if required (you can skip this if already installed)
        python -m pip install "${{ github.workspace }}\src\bin\python\pyglet-1.2.0-py2-none-any.whl"

    - name: Build with py2exe
      run: |
        cd src
        python setup.py py2exe

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: snakes-etc-on-a-plain-win32
        path: release/win32  # Adjust to your actual build output path
