name: Windows Build

on:
  push:
    branches:
      - master  # Change this to your release branch

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download and Install Python 2.7 (32-bit)
        run: |
          Invoke-WebRequest -Uri "https://www.python.org/ftp/python/2.7.18/python-2.7.18.msi" -OutFile "python.msi"
          Start-Process msiexec.exe -ArgumentList '/i python.msi /quiet /qn /norestart' -NoNewWindow -Wait
          echo "C:\Python27" | Out-File -Append -Encoding utf8 $env:GITHUB_PATH

      - name: Verify Python Installation
        run: |
          python --version
          pip --version

      - name: Install Dependencies
        run: |
          cd src
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Executable with py2exe
        run: |
          cd src
          python setup.py install
          python setup.py py2exe

      - name: Package Executable
        run: |
          mkdir release
          mv src/dist/* release/
          tar -cvf game-win32.tar release/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: game-win32
          path: game-win32.tar

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/heads/main')
        with:
          files: game-win32.tar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
