name: Build Game for Windows

on:
  push:
    branches:
      - master  # or your desired branch to trigger the build

jobs:
  build:
    runs-on: windows-latest  # or use self-hosted if you have a custom runner

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Install Python 2.7.18 using MSI installer
      run: |
        $python_installer = "${{ github.workspace }}\src\bin\python\python-2.7.18.msi"
        msiexec /i $python_installer /quiet /norestart

    - name: Add Python 2.7 to PATH for this session
      run: |
        $env:PATH = "C:\Python27\;$env:PATH"
        python --version
        where python

    - name: Install pip using bundled ensurepip
      run: |
        python -m ensurepip --default-pip
        python -m pip --version

    - name: Install pyglet from .whl file
      run: |
        cd src\bin\python
        python -m pip install pyglet-1.2.0-py2-none-any.whl

    - name: Install dependencies (py2exe, etc.) and Build
      run: |
        cd src
        python -m pip install -r requirements.txt  # Doesn't install pyglet, since it's already installed
        python setup.py py2exe

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: snakes-etc-on-a-plain-win32
        path: release/win32  # Adjust to your actual build output path
